name: robertburns.me
permalink: /blog/:title
pygments: true
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Blog
  url: /blog/
- text: Projects
  url: /projects/
- text: Contact
  url: /contact/
#- text: Blog
#  url: /en/blog/
#  layout: post